

const quantumTitle = [
    {
        title: "Quantum Computing"
    },
    {
        title: "Post-Quantum Cryptography"
    },
    {
        title: "Quantum Communications"
    },
    {
        title: "Quantum Sensors"
    }
]

const quantum = [
    [
        {
            subTitle: "Accelerated Algorithm Development",
            images: "/QuantumAlgorithmDevelopment.png",
            description: "Leveraging AI, vast datasets of potential quantum algorithms can be analyzed to predict promising candidates for specific tasks, significantly expediting the algorithm development process."
        },
        {
            subTitle: "Error Correction and Fault Tolerance",
            images: "/ErrorCorrection.png",
            description: "HailAgi can contribute to the development of advanced error correction techniques, ensuring qubit stability and reducing errors in quantum calculations—a crucial aspect in building reliable quantum computers."
        },
        {
            subTitle: "Optimization of Hardware and Software",
            images: "/OptimizingHardwareAndSoftware.png",
            description: "AI has the capability to optimize both quantum hardware and software designs, enhancing the overall performance and efficiency of quantum computers."
        }
    ],
    [
        {
            subTitle: "Discovery and Evaluation of Algorithms",
            images: "/QuantumAlgorithmDiscovery.png",
            description: "HailAgi can analyze mathematical structures to identify potential post-quantum cryptographic algorithms, accelerating the search for robust solutions in the post-quantum era."
        },
        {
            subTitle: "Simulation of Quantum Attacks",
            images: "/QuantumAttack.png",
            description: "AI-driven simulations of attacks on cryptographic algorithms by quantum computers can assess vulnerabilities and aid in refining post-quantum cryptography systems."
        },
        {
            subTitle: "Automation of Cryptanalysis and Vulnerability Detection",
            images: "/QuantumAutomation.png",
            description: "HailAgi can automate the process of analyzing and comparing various post-quantum cryptography algorithms, identifying potential weaknesses and ensuring long-term security."
        }
    ],
    [
        {
            subTitle: "Optimization of Quantum Networks",
            images: "/QuantumNetwork.png",
            description: " HailAgi is instrumental in designing and optimizing quantum communication networks, considering factors such as topology, noise levels, and security requirements."
        },
        {
            subTitle: "Efficient Protocol Development and Routing Algorithms",
            images: "/QuantumRoutingAlgorithm.png",
            description: "HailAgi can create efficient protocols for transmitting information using entangled particles and optimize routing algorithms for quantum networks."
        },
        {
            subTitle: "Automation of Network Management and Security",
            images: "/QuantumNetworkSecurity.png",
            description: "AI-powered systems can automate the management and security of quantum networks, detecting potential threats and implementing countermeasures to uphold secure communication."
        }
    ],
    [
        {
            subTitle: "Designing Ultra-Sensitive Sensors",
            images: "/QuantumSensitiveSensor.png",
            description: " HailAgi can play a key role in designing innovative quantum sensors with optimal sensitivity and performance tailored for specific applications."
        },
        {
            subTitle: "Data Analysis and Interpretation",
            images: "/QuantumDataAnalysis.png",
            description: "AI is adept at analyzing complex data generated by quantum sensors, identifying patterns, extracting insights, and facilitating accurate interpretation of measured quantities."
        },
        {
            subTitle: "Real-time Feedback and Adaptive Control",
            images: "/QuantumRealTImeFeedback.png",
            description: "HailAgi can provide real-time feedback and adaptive control for quantum sensors, enhancing their accuracy and sensitivity in dynamic real-time situations."
        }
    ]
]

const Quantum = () => {
    return (
        <div className="pt-11 background-div-color">
            {quantumTitle.map((item, index) => (
                <div key={index}>
                    <h3 className="text-center text-2xl font-bold pt-8 pb-4 text-black px-5">
                        {item.title}
                    </h3>
                    <div className="flex flex-wrap justify-around pb-4 lg:flex">
                        {quantum[index].map((item, index) => (
                            <div key={index} className="w-full sm:w-full md:w-[90%] lg:w-customWidth m-2 py-2 px-4 shadow-md background-div-color rounded-lg flex flex-col items-center">
                                <img src={item.images} height={70} width={90} alt="Your Image" className="my-4" />
                                <p className="text-center font-bold text-lg mb-3">{item.subTitle}</p>
                                <p className="text-justify">
                                    {item.description}
                                </p>
                            </div>
                        ))}
                    </div>
                    <div className=" border-[#18191B] border-4"></div>
                </div>
            ))}
        </div>
    )
}

export default Quantum