import NavigationMenu, { NavigationMenuBar } from "@/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import DefaultNavbar from "@/components/NavBar";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HailAgi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
